### ISSUE TITLE
'DartWalker3dEnv' object has no attribute 'assist_schedule'

### ISSUE THREAD

**Issue by GaoPeng97** [VincentYu68/SymmetryCurriculumLocomotion#2]
sorry to bother you again, when I build everything up and run this command:
   mpirun -np 8 python -m baselines.ppo1.run_walker3d_staged_learning
I got some error message like this: 
   /////////////////////////////////////////////////////////////////////////////////////////////////////////
 Traceback (most recent call last):
  File "/home/o2/Downloads/yes/envs/py3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/o2/Downloads/yes/envs/py3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/o2/Desktop/RL/biped/SymmetryCurriculumLocomotion/baselines/baselines/ppo1/run_walker3d_staged_learning.py", line 138, in <module>
    main()
  File "/home/o2/Desktop/RL/biped/SymmetryCurriculumLocomotion/baselines/baselines/ppo1/run_walker3d_staged_learning.py", line 134, in main
    train_mirror(args.env, num_timesteps=int(5000 * 4 * 800), seed=args.seed)
  File "/home/o2/Desktop/RL/biped/SymmetryCurriculumLocomotion/baselines/baselines/ppo1/run_walker3d_staged_learning.py", line 73, in train_mirror
    rollout_length_threshold = env.env.env.assist_schedule[2][0]/env.env.env.dt
AttributeError: 'DartWalker3dEnv' object has no attribute 'assist_schedule'
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

and if I run the other command such as :
  mpirun -np 8 python -m baselines.ppo1.run_hexapod_staged_learning
there is something like this 
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
line 126, in <module>
    main()
  File "/home/o2/Desktop/RL/biped/SymmetryCurriculumLocomotion/baselines/baselines/ppo1/run_hexapod_staged_learning.py", line 122, in main
    train_mirror(args.env, num_timesteps=int(5000*4*800), seed=args.seed)
  File "/home/o2/Desktop/RL/biped/SymmetryCurriculumLocomotion/baselines/baselines/ppo1/run_hexapod_staged_learning.py", line 36, in train_mirror
    env = gym.make(env_id)
  File "/home/o2/dartForPy3/dart/build/dart-env/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/o2/dartForPy3/dart/build/dart-env/gym/envs/registration.py", line 118, in make
    spec = self.spec(id)
  File "/home/o2/dartForPy3/dart/build/dart-env/gym/envs/registration.py", line 153, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: DartHexapod-v1
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by GaoPeng97** [comment]
Would please have a look on that and give me some suggestions to solve that when you are free, thanks very much    >_<

**Comment by VincentYu68** [comment]
It seems like you are using the original dart-env instead of the ones provided in this repository. Can you try navigating to the dart-env in this repository and do 'pip install -e .'?

**Comment by GaoPeng97** [comment]
It works, thank you very much.

**Comment by GaoPeng97** [comment]
May I ask how to build my own model (.skel file), is there any simple and useful tool?

**Comment by VincentYu68** [comment]
You can find the specifications for .skel files here: http://dartsim.github.io/skel_file_format.html#hierarchy

I usually build new models by adapting existing .skel files. There aren't any tools with GUI for building models yet.

**Comment by GaoPeng97** [comment]
Sorry, if there is something missing in this documentation, i mean the type of joint is not completely specified, there is only "revolute", but I saw that you use "weld" "universal " and something others, what do they mean? 

![screenshot from 2018-08-11 21-36-39](https://user-images.githubusercontent.com/22500679/43992262-66a750c4-9daf-11e8-859a-27898d67c0e7.png)

**Comment by VincentYu68** [comment]
It seems like the joint types are not fully documented...  Besides 'revolute' joint, there are 'weld', 'prismatic', 'universal', 'euler', 'translational', and possibly others. 'weld' means the joint has no degrees of freedom, i.e. it is rigidly attached to the parent node. 'prismatic' has one translational dof, with the direction specified by <axis></axis>. 'universal' is 2 dof rotational joint and 'euler' is 3 dof rotational joint. 'translational' has 3 dofs for translation in x, y and z.
